{% set name = "pink" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/pin-{{ name }}/pin_{{ name }}-{{ version }}.tar.gz
  sha256: 21ffbb4624377d74036c4c4d1d9ba252a0c912cd7a2469117e768f36179c17e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - loop-rate-limiters >=0.1.0
    - numpy >=1.19.0
    - osqp
    - pinocchio >=2.6.3
    - proxsuite
    - qpsolvers >=2.5.0
    - quadprog >=0.1.11
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - pink

about:
  home: https://pypi.org/project/pin-pink
  summary: Inverse kinematics for articulated robot models, based on Pinocchio.
  dev_url: https://github.com/stephane-caron/pink
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
