{% set name = "pink" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/pin-{{ name }}/pin_{{ name }}-{{ version }}.tar.gz
  sha256: 7ce58ee380f6ab0bc037063d0aaac3472a92538be932db137f680a05087330a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - loop-rate-limiters >=0.1.0
    - numpy >=1.19.0
    - osqp
    - pinocchio >=2.6.3
    - proxsuite
    - qpsolvers >=2.5.0
    - quadprog >=0.1.11

test:
  requires:
    - python {{ python_min }}
  imports:
    - pink

about:
  home: https://pypi.org/project/pin-pink
  summary: Inverse kinematics for articulated robot models, based on Pinocchio.
  dev_url: https://github.com/stephane-caron/pink
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
