{% set name = "pink" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/pin-{{ name }}/pin_{{ name }}-{{ version }}.tar.gz
  sha256: e099e6c6e8e3d159aca04e08119b536081944a797d46962e7d57e0327c1ed8b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.8
    - loop-rate-limiters >=0.1.0
    - numpy >=1.19.0
    - osqp
    - pinocchio >=2.6.3
    - proxsuite
    - qpsolvers >=2.5.0
    - quadprog >=0.1.11

test:
  imports:
    - pink

about:
  home: https://pypi.org/project/pin-pink
  summary: Inverse kinematics for articulated robot models, based on Pinocchio.
  dev_url: https://github.com/stephane-caron/pink
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
